services:
  moneysystem:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_BASE_URL=http://localhost:3000
    restart: unless-stopped


